In [2]:
import numpy as np
import cv2

In [11]:
img = cv2.imread('friends.jpg')

cv2.imshow('image',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
#load cascade classifier
haar = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [15]:
image = img.copy()

#step-1: convert image to grayscale
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
#step-2: apply grayscale image to cascade classifier
face_rect = haar.detectMultiScale(gray,1.3,5)
#step-3: draw bounding box
for x,y,w,h in face_rect:
    cv2.rectangle(image,(x,y),(x+w, y+h),(0,255,0),2)

cv2.imshow('detected faces',image)
cv2.waitKey()
cv2.destroyAllWindows()


In [16]:
print(face_rect)

[[127 107  97  97]
 [256  88  98  98]
 [405  90  99  99]]


### real-time face detection using opencv

In [24]:
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if ret == False:
        break

    image = frame.copy()
    
    #step-1: convert image to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    #step-2: apply grayscale image to cascade classifier
    face_rect = haar.detectMultiScale(gray,1.3,5)
    #step-3: draw bounding box
    for x,y,w,h in face_rect:
        cv2.rectangle(image,(x,y),(x+w, y+h),(0,255,0),2)
        
    cv2.imshow('detected faces',image )

    if cv2.waitKey(1) == 27:
        break
         
cap.release()
cv2.destroyAllWindows()